@startuml
package ohm.softa.a05 {

    +class PlantBed<T> {
        -plants: SimpleList<T>

        +add(plant: T)
        +size(): int
        +getPlantsByColor(color: ohm.softa.a05.model.PlantColor): SimpleList<T>
    }
}
@enduml
