@startuml
package java.lang {
    
    interface ohm.softa.a05.model.Comparable<T> {
        +compareTo(other: T): int
    }
}

package ohm.softa.a05.model {
        +enum ohm.softa.a05.model.PlantColor {
            GREEN,
            YELLOW,
            RED,
            BLUE,
            ORANGE
        }

        +abstract class ohm.softa.a05.model.Plant implements ohm.softa.a05.model.Comparable {
            -height: double
            -family: String
            -name: String

            +getHeight(): double
            +getFamily(): String
            +getName(): String
            +{abstract} getColor(): ohm.softa.a05.model.PlantColor
        }

        +class ohm.softa.a05.model.Flower extends ohm.softa.a05.model.Plant {
        }

        +class ohm.softa.a05.model.Shrub extends ohm.softa.a05.model.Plant{
        }
    }
@enduml